flowchart TD
    Confluence["Confluence"] -->|"A1  A1  A2  A2  A4.0  A21  A21  A22.0  A24  A34  A36.0"| Confluence["Confluence"]
    Confluence["Confluence"] -->|"A24  A22  A2  A4.0"| Jira["Jira"]
    Jira["Jira"] -->|"A29  A29.0  A329  A333  A335"| Jira["Jira"]
    Jira["Jira"] -->|"A29  A29"| Confluence["Confluence"]
    Confluence["Confluence"] -->|"A39  A39  A39"| Jbehave["Jbehave"]
    Jbehave["Jbehave"] -->|"A40  A42.0  A40  A42.0"| Jbehave["Jbehave"]
    Confluence["Confluence"] -->|"A2  A4.0"| Puppet["Puppet"]
    Puppet["Puppet"] -->|"A98  A98"| Puppet["Puppet"]
    ServiceNow["ServiceNow"] -->|"A128  A128  A273.0"| Puppet["Puppet"]
    Puppet["Puppet"] -->|"A115  A113  A136.0"| ServiceNow["ServiceNow"]
    ServiceNow["ServiceNow"] -->|"A127  A127"| ServiceNow["ServiceNow"]
    ServiceNow["ServiceNow"] --> Text["Text"]
    ServiceNow["ServiceNow"] --> Flyway["Flyway"]
    _UNIX_LINUX_["(UNIX/LINUX)"] --> SonarQube["SonarQube"]
    SonarQube["SonarQube"] --> GitHub["GitHub"]
    Flyway["Flyway"] --> Flyway["Flyway"]
    GitLab["GitLab"] --> Maven["Maven"]
    GitLab["GitLab"] --> Selenium["Selenium"]
    Flyway["Flyway"] --> Selenium["Selenium"]
    Jbehave["Jbehave"] -->|"A46  A47"| Selenium["Selenium"]
    Jbehave["Jbehave"] -->|"A46  A47"| Jmeter["Jmeter"]
    Jira["Jira"] -->|"A50.0  A50.0"| Jmeter["Jmeter"]
    Selenium["Selenium"] -->|"A279  A280"| Selenium["Selenium"]
    Jmeter["Jmeter"] -->|"A283  A284"| Jmeter["Jmeter"]
    Selenium["Selenium"] -->|"A305  A306.0"| Jira["Jira"]
    Jmeter["Jmeter"] -->|"A309.0  A310.0"| Jira["Jira"]
    Jira["Jira"] --> Text["Text"]
    _UNIX_LINUX_["(UNIX/LINUX)"] --> Jira["Jira"]
    Jira["Jira"] --> XL["XL"]
    Deploy["Deploy"] --> XL["XL"]
    OverOps["OverOps"] --> XL["XL"]
    Deploy["Deploy"] -->|"A352  A354.0"| OverOps["OverOps"]
    classDef cls__ADD8E6 fill:#ADD8E6,stroke:#333,color:#fff
    class Confluence,Jira,Jbehave,Puppet,ServiceNow,Flyway,SonarQube,Maven,Selenium,Jmeter,OverOps cls__ADD8E6